### ISSUE TITLE
Speaking code 

### ISSUE THREAD

**Issue by askaalyy** [askaalyy/components-on-a-grid#1]
@thatkidmadrid

Here is my recording
[aly-aska-components-on-a-grids.m4a.zip](https://github.com/askaalyy/components-on-a-grid/files/7238780/aly-aska-components-on-a-grids.m4a.zip)

**Comment by thatkidmadrid** [comment]
Looks and sounds good!
I think you're saying `selector` but you can just say `select` as in the present tense of the verb `to select`
other than that nothing to comment on for speaking the code 👍 

I think you're missing just the css property to hide the bullet for the list items in the nav, but it looks like you were able to match the reference so I'll give you the full marks

EDIT: I notice that markbot did not let you submit because it's too different from the reference. Removing the margins on your `figure`s should get things a lot closer. Revisit this before the end of class and I will accept it. I'll go over the solution quickly in the beginning of class

**Comment by askaalyy** [comment]
Thank you, I will re-look at it before the end of class.
